### ISSUE TITLE
add https://osintframework.com/ somewhere?

### ISSUE THREAD

**Issue by FeljxFeljx** [edoardottt/awesome-hacker-search-engines#1]
I think https://osintframework.com/ is also usefull since it has stored a lot of great tools

**Comment by edoardottt** [comment]
omg thank you so much!!!! Didn't know about that :1st_place_medal:  

Actually, I can't add osintframework.com as a single item. I'll look at all the services they list and add every single useful service in the appropriate section :)

Thank u !!
