### ISSUE TITLE
Add yup

### ISSUE THREAD

**Issue by marban** [edoardottt/awesome-hacker-search-engines#10]
General 
https://yup.is — Real-time News with zero tracking/cookies

**Comment by edoardottt** [comment]
Hi @marban, thanks for your interest in this project.
Maybe I should state it clearly, but the search engines/services listed here are not just products with security or privacy in mind, but they are tools that an hacker effectively could use while performing security tests and other cybersec related activities. 
So, I don't think the product you're suggesting fits well in the list, sorry I hope you can understand.

I appreciate so much this type of contribution, if you want you can submit all the issue/pull request you want :)
Have a nice day!
