### ISSUE TITLE
Add https://www.geocam.ru/en/ to cameras section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#110]
Add https://www.geocam.ru/en/ to cameras section

**Comment by DevanshKyada27** [comment]
Hey @edoardottt can I work on this issue.

**Comment by edoardottt** [comment]
Done @DevanshKyada27

**Comment by edoardottt** [comment]
Completed, thanks @DevanshKyada27 !
