### ISSUE TITLE
Add https://livetraffic.eu/ to cameras section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#111]
Add https://livetraffic.eu/ to cameras section

**Comment by DevanshKyada27** [comment]
Hey @edoardottt can you assign this issue to me, want to work on it.

**Comment by edoardottt** [comment]
Done @DevanshKyada27

**Comment by edoardottt** [comment]
Completed, thanks @DevanshKyada27 !
