### ISSUE TITLE
Add https://www.earthcam.com/ to cameras section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#113]
Add https://www.earthcam.com/ to cameras section

**Comment by rsk2** [comment]
Hi @edoardottt, can I work on this issue?

**Comment by edoardottt** [comment]
Done @rsk2

**Comment by chinmay7016** [comment]
Hey @edoardottt can I also contribute on this issue if @rsk2 is not doing

**Comment by edoardottt** [comment]
Completed, thanks @rsk2 !

**Comment by rsk2** [comment]
Thanks @edoardottt!
