### ISSUE TITLE
Add https://www.webcamtaxi.com/en/ to cameras section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#114]
Add https://www.webcamtaxi.com/en/ to cameras section

**Comment by manavb2214** [comment]
Hey @edoardottt please assign this issue to me.

**Comment by manavb2214** [comment]
Hey @edoardottt ! If you like it you can merge it !!!

**Comment by edoardottt** [comment]
Completed, thanks @manavb2214 !
