### ISSUE TITLE
Add https://scriptmafia.org/ to Code section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#127]
Add https://scriptmafia.org/ to Code section

**Comment by Pakeetharan** [comment]
@edoardottt could you please assign this to me?

**Comment by edoardottt** [comment]
Done @Pakeetharan

**Comment by DevanshKyada27** [comment]
Hey @edoardottt can you assign this issue to me.

**Comment by DevanshKyada27** [comment]
Ok no problem @edoardottt :)

**Comment by chinmay7016** [comment]
Sir @edoardottt there is no update from pakeetharan side sir can you pls assign this to me I would be quickly doing it sir

**Comment by edoardottt** [comment]
Completed, thanks @Pakeetharan !
