### ISSUE TITLE
Add https://clearbit.com/resources/tools/connect to mail addresses section

### ISSUE THREAD

**Issue by chinmay7016** [edoardottt/awesome-hacker-search-engines#148]
hey @edoardottt i have a request to add https://clearbit.com/resources/tools/connect to mail addresses section

Clearbit Connect: A Gmail extension that helps you find email addresses and other information about your contacts.

@edoardottt  pls add hacktober fest label to it

**Comment by chinmay7016** [comment]
@ExitoLab pls assign this issue to me

**Comment by edoardottt** [comment]
I already know this product, but it's an extension not an online service
