### ISSUE TITLE
Bug - Grammar mistake in README.md.

### ISSUE THREAD

**Issue by ayushrakesh** [edoardottt/awesome-hacker-search-engines#153]
I have noticed a small grammar mistake in **README.md** file inside section "**Servers**".

"**Discover, Research and Monitor any..**"  should be "**Discover, Research, and Monitor any...**"

Below I have attached the screenshot of it.

![Screenshot (81)](https://github.com/edoardottt/awesome-hacker-search-engines/assets/115995339/94725b4f-4ab1-4564-bad0-6ff531205f18)

**Comment by ayushrakesh** [comment]
Please assign this issue to me.

**Comment by edoardottt** [comment]
It's a not a typo, this is the description of the product in the official page

![Screenshot from 2023-10-21 11-14-16](https://github.com/edoardottt/awesome-hacker-search-engines/assets/35783570/a2a9cb59-edb2-4dcb-a0cd-ca2d759201a2)
