### ISSUE TITLE
Add https://www.paloaltonetworks.com/cortex/cortex-xpanse to attack surface section

### ISSUE THREAD

**Issue by chinmay7016** [edoardottt/awesome-hacker-search-engines#156]
Expanse offers a platform for attack surface management that helps organizations discover and monitor their internet-connected assets, identify vulnerabilities, and enhance their cybersecurity posture. It provides insights into your organization's global internet assets, helping you proactively manage and secure your digital footprint.

https://www.paloaltonetworks.com/cortex/cortex-xpanse

**Comment by harshvyas-22** [comment]
i would love to contribute please assign to  me
