### ISSUE TITLE
Add https://emailrep.io/ to email section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#161]
Add https://emailrep.io/ to email section

**Comment by harshvyas-22** [comment]
i want to make contribution in this can you assign it to mt

**Comment by edoardottt** [comment]
Done @harshvyas-22

**Comment by harshvyas-22** [comment]
Could you please clarify in which file to add this @edoardottt

**Comment by edoardottt** [comment]
In the README.md, here https://github.com/edoardottt/awesome-hacker-search-engines#mail-addresses

See other PRs.

**Comment by harshvyas-22** [comment]
Updated

**Comment by edoardottt** [comment]
Completed, thanks @harshvyas-22 !
