### ISSUE TITLE
Add https://ecosyste.ms/ to code section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#184]
Add https://ecosyste.ms/ to code section

**Comment by harshvyas-22** [comment]
i would love to contribute please assign to me

**Comment by edoardottt** [comment]
Done @harshvyas-22

**Comment by harshvyas-22** [comment]
where to put this in unclassified?

**Comment by edoardottt** [comment]
it's written in the title and description of the issue, code section

**Comment by harshvyas-22** [comment]
Created the pr #188

**Comment by edoardottt** [comment]
Completed, thanks @harshvyas-22 !
