### ISSUE TITLE
Add LeakPeek

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#242]
Add this row below to the category `Leaks`
```
- [LeakPeek](https://leakpeek.com/) - Search for your publicly leaked passwords using an email or username, secure your personal data
```

**Comment by RajatX24** [comment]
Hello,

I am interested in working on this issue. Can you please assign it to me?

**Comment by edoardottt** [comment]
Please go ahead @RajatX24 : )

**Comment by RajatX24** [comment]
Hey @edoardottt ,

I have made a pull request regarding this issue.
You can check it out here:https://github.com/edoardottt/awesome-hacker-search-engines/pull/245

Please review it and let me know.

Thanks

**Comment by edoardottt** [comment]
Thanks @RajatX24 for your contribution! 

Appreciated
