### ISSUE TITLE
add cvefeed.io

### ISSUE THREAD

**Issue by micaelmaciel** [edoardottt/awesome-hacker-search-engines#265]
maybe add [feed.io](https://cvefeed.io/)? it's more of a redirection website to several git repos and found references on cves, but it digs some quite obscure links to some cves, so it could be useful

**Comment by edoardottt** [comment]
Added under Vulnerabilities category https://github.com/edoardottt/awesome-hacker-search-engines?tab=readme-ov-file#vulnerabilities

Thanks @micaelmaciel for your contribution!
