### ISSUE TITLE
Add S4E to Attack Surface Category

### ISSUE THREAD

**Issue by haci-s4e** [edoardottt/awesome-hacker-search-engines#267]
Hello,

Could you please add s4e.io to the attack surface category?

[s4e.io](https://s4e.io/) - S4E is a Continuous Threat Exposure Management (CTEM) platform that offers a web-based cybersecurity solution for comprehensive scanning and vulnerability detection of digital assets like domains, subdomains, IP addresses, and web apps.

Sincerely.

**Comment by edoardottt** [comment]
Added. Thanks for your contribution @haci-s4e : )
