### ISSUE TITLE
insta

### ISSUE THREAD

**Issue by HEMANTJADHAV5566** [edoardottt/awesome-hacker-search-engines#269]
> instagram
> 
> 
> 
> 
> 
> 
> 
>  

 _Originally posted by @HEMANTJADHAV5566 in [2fa5e29](https://github.com/edoardottt/awesome-hacker-search-engines/commit/2fa5e29e57b2510a77d45ffd3021cade280bd5b1#r150650259)_

**Comment by edoardottt** [comment]
Instagram Is already present under social networks category
