### ISSUE TITLE
Add https://snov.io/email-finder

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#41]
Add https://snov.io/email-finder

**Comment by ExitoLab** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by ExitoLab** [comment]
Please review this PR [#73](https://github.com/edoardottt/awesome-hacker-search-engines/pull/73)

**Comment by ExitoLab** [comment]
Please review this new PR [#76](https://github.com/edoardottt/awesome-hacker-search-engines/pull/76)

**Comment by edoardottt** [comment]
Completed! thanks @ExitoLab
