### ISSUE TITLE
Add https://flickr.com/search/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#46]
Add https://flickr.com/search/ to image section

**Comment by ExitoLab** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by ExitoLab** [comment]
Please review this PR [#72](https://github.com/edoardottt/awesome-hacker-search-engines/pull/72)

**Comment by ExitoLab** [comment]
Pls review this PR [#75](https://github.com/edoardottt/awesome-hacker-search-engines/pull/75)

**Comment by edoardottt** [comment]
Completed! thanks @ExitoLab !
