### ISSUE TITLE
Add https://images.google.com/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#47]
Add https://images.google.com/ to image section

**Comment by ExitoLab** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by ExitoLab** [comment]
Please review this PR [#71](https://github.com/edoardottt/awesome-hacker-search-engines/pull/71)

**Comment by edoardottt** [comment]
completed, thanks @ExitoLab !
