### ISSUE TITLE
Add https://infringement.report/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#48]
Add https://infringement.report/ to image section

**Comment by ExitoLab** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by ExitoLab** [comment]
Pls do review this PR [#70](https://github.com/edoardottt/awesome-hacker-search-engines/pull/70)

**Comment by edoardottt** [comment]
completed, thanks @ExitoLab !
