### ISSUE TITLE
Add http://www.pictriev.com/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#50]
Add http://www.pictriev.com/ to image section

**Comment by ExitoLab** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by ExitoLab** [comment]
Pls review this PR [#68](https://github.com/edoardottt/awesome-hacker-search-engines/pull/68)

**Comment by edoardottt** [comment]
completed, thanks @ExitoLab !
