### ISSUE TITLE
Add https://pimeyes.com/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#51]
Add https://pimeyes.com/ to image section

**Comment by ExitoLab** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by ExitoLab** [comment]
Please do review this PR [#67](https://github.com/edoardottt/awesome-hacker-search-engines/pull/67)

**Comment by edoardottt** [comment]
completed, thanks @ExitoLab !
