### ISSUE TITLE
Add https://reverseimage.net/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#61]
Add https://reverseimage.net/ to image section

**Comment by ExitoLab** [comment]
Please assign this issue to me, I would like to work on it.

**Comment by ExitoLab** [comment]
Pls review this PR [65](https://github.com/edoardottt/awesome-hacker-search-engines/pull/65/files)

**Comment by edoardottt** [comment]
completed, thanks @ExitoLab !
