### ISSUE TITLE
Add https://www.pixsy.com/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#63]
Add https://www.pixsy.com/ to image section

**Comment by jude-san** [comment]
can you please explain more about the issue?

**Comment by edoardottt** [comment]
hi @jude-san, of course!  
You just have to add an entry in the README file [here at the end of images section](https://github.com/edoardottt/awesome-hacker-search-engines#images) adding this:

```
- [Pixsy](https://www.pixsy.com/) - Find and fight image theft
```


let me know if you want I assing this to you.

**Comment by jude-san** [comment]
@edoardottt ok, got it. 
please assign the task to me.

**Comment by edoardottt** [comment]
done, for any doubt ping me!

**Comment by edoardottt** [comment]
completed, thanks @jude-san !
