### ISSUE TITLE
Add https://same.energy/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#77]
Add https://same.energy/ to image section

**Comment by ExitoLab** [comment]
@edoardottt  please assign this issue to me

**Comment by ExitoLab** [comment]
Pls review this PR [#90](https://github.com/edoardottt/awesome-hacker-search-engines/pull/90)

**Comment by edoardottt** [comment]
Completed, thanks @ExitoLab !
