### ISSUE TITLE
Add https://fotoforensics.com/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#78]
Add https://fotoforensics.com/ to image section

**Comment by ExitoLab** [comment]
@edoardottt  please assign this issue to me

**Comment by chinmay7016** [comment]
hey @edoardottt can you pls verify this and merge this

**Comment by ExitoLab** [comment]
@edoardottt  pls use @chinmay7016  PR

**Comment by Creativecuts45** [comment]
@edoardottt pls merge it
