### ISSUE TITLE
Add http://exifdata.com/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#80]
Add http://exifdata.com/ to image section

**Comment by ExitoLab** [comment]
@edoardottt  please assign this issue to me

**Comment by chinmay7016** [comment]
pls review and merge it

**Comment by ExitoLab** [comment]
@edoardottt  pls use @chinmay7016  PR 

@chinmay7016  pls go for it..

**Comment by Creativecuts45** [comment]
Can u pls merge it
