### ISSUE TITLE
Add https://pic.sogou.com/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#82]
Add https://pic.sogou.com/ to image section

**Comment by ExitoLab** [comment]
@edoardottt  please assign this issue to me

**Comment by ExitoLab** [comment]
Pls review PR [#85](https://github.com/edoardottt/awesome-hacker-search-engines/pull/85)

**Comment by edoardottt** [comment]
Completed, thanks @ExitoLab !
