### ISSUE TITLE
Add https://pixabay.com/ to image section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#83]
Add https://pixabay.com/ to image section

**Comment by goobric** [comment]
!issue
hi, can I please be assigned to work on this issue #83
thanks

**Comment by edoardottt** [comment]
Absolutely yes! If you need help/guidance let me know :)

**Comment by DevanshKyada27** [comment]
Hey @edoardottt can you please assign this issue to me.

**Comment by edoardottt** [comment]
any update? @goobric

**Comment by DevanshKyada27** [comment]
Hey @edoardottt if you like the PR you can merge it :)

**Comment by edoardottt** [comment]
Completed, thanks @DevanshKyada27 !

**Comment by DevanshKyada27** [comment]
Thanks @edoardottt :)
