### ISSUE TITLE
Add https://haveibeenzuckered.com/ to leaks section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#88]
Add https://haveibeenzuckered.com/ to leaks section

**Comment by ExitoLab** [comment]
@edoardottt please assign this issue to me

**Comment by edoardottt** [comment]
done @ExitoLab

**Comment by DevanshKyada27** [comment]
Hey @edoardottt can you please assign this issue to me.

**Comment by ExitoLab** [comment]
@DevanshKyada27  go for it.. @edoardottt  pls use @DevanshKyada27  PR

**Comment by edoardottt** [comment]
Completed, thanks @DevanshKyada27

**Comment by DevanshKyada27** [comment]
Thanks @edoardottt looking forward for to work with you:)
