### ISSUE TITLE
Add https://ddosecrets.com/ to leaks section

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/awesome-hacker-search-engines#89]
Add https://ddosecrets.com/ to leaks section

**Comment by ExitoLab** [comment]
@edoardottt please assign this issue to me

**Comment by edoardottt** [comment]
done @ExitoLab

**Comment by DevanshKyada27** [comment]
Hey @edoardottt can you please assign this issue to me, want to work on it.

**Comment by ExitoLab** [comment]
@edoardottt  pls review PR [#129](https://github.com/edoardottt/awesome-hacker-search-engines/pull/129)

**Comment by ExitoLab** [comment]
@edoardottt pls use @DevanshKyada27  PR

**Comment by edoardottt** [comment]
Completed, thanks @DevanshKyada27 !
