### ISSUE TITLE
Please add DuckDuckGo to 'General Search Engines' list

### ISSUE THREAD

**Issue by Am0rphous** [edoardottt/awesome-hacker-search-engines#9]
Hi!

Please add DuckDuckGo to "General Search Engines" list:
````
- [DuckDuckGo](https://duckduckgo.com/)
````
Best regards

**Comment by edoardottt** [comment]
Hi, thank you for your interest in this project.
I already thought about it, but I discovered it's a simple wrapper aroung Bing. For this reason I don't think it's worth adding.

For other suggestions I'm here ready to reply. Have a nice day :)
